# **Exercises - Filtering and Aggregations using SQL**

Let us take care of exercises related to filtering and aggregations using SQL.
* Get all the details of the courses which are in `inactive` or `draft` state.
* Get all the details of the courses which are related to `Python` or `Scala`.
* Get count of courses by `course_status`. The output should contain `course_status` and `course_count`.
* Get count of `published` courses by `course_author`. The output should contain `course_author` and `course_count`.
* Get all the details of `Python` or `Scala` related courses in `draft` status.
* Get the author and count where the author have more than **one published** course. The output should contain `course_author` and `course_count`.

In [3]:
!pip install ipython-sql sqlalchemy

Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl.metadata (17 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.48-py3-none-any.whl.metadata (9.5 kB)
Collecting prettytable (from ipython-sql)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: ipython in /opt/miniconda3/lib/python3.13/site-packages (from ipython-sql) (9.1.0)
Collecting sqlparse (from ipython-sql)
  Downloading sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: six in /opt/miniconda3/lib/python3.13/site-packages (from ipython-sql) (1.17.0)
Collecting ipython-genutils (from ipython-sql)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.2-cp313-cp313-macosx_11_0_universal2.whl.metadata (3.7 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/miniconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: decorator in /opt/miniconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: ipython-pygments-lexers in /opt/miniconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/miniconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/miniconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: pexpect>4.3 in /opt/miniconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/miniconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /opt/miniconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack_data in /opt/miniconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in /opt/miniconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: wcwidth in /opt/miniconda3/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/miniconda3/lib/python3.13/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /opt/miniconda3/lib/python3.13/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing in /opt/miniconda3/lib/python3.13/site-packages (from stack_data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in /opt/miniconda3/lib/python3.13/site-packages (from stack_data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure-eval in /opt/miniconda3/lib/python3.13/site-packages (from stack_data->ipython->ipython-sql) (0.2.2)
Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Downloading sqlalchemy-2.0.48-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 36.8 MB/s  0:00:00
Downloading greenlet-3.3.2-cp313-cp313-macosx_11_0_universal2.whl (279 kB)
Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading sqlparse-0.5.5-py3-none-any.whl (46 kB)
Installing collected packages: ipython-genutils, sqlparse, prettytable, greenlet, sqlalchemy, ipython-sql
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [ipython-sql] [ipython-sql]
Successfully installed greenlet-3.3.2 ipython-genutils-0.2.0 ipython-sql-0.5.0 prettytable-3.17.0 sqlalchemy-2.0.48 sqlparse-0.5.5

In [4]:
%load_ext sql

In [9]:
%env DATABASE_URL=postgresql://itversity_sms_user:itversity@localhost:5432/itversity_sms_db

env: DATABASE_URL=postgresql://itversity_sms_user:itversity@localhost:5432/itversity_sms_db

In [11]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp313-cp313-macosx_10_13_x86_64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.11-cp313-cp313-macosx_10_13_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 43.0 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [12]:
%%sql

CREATE TABLE courses (
    course_id SERIAL PRIMARY KEY,
    course_name VARCHAR(60),
    course_author VARCHAR(40),
    course_status VARCHAR(9),
    course_published_dt DATE
);

Done.

[]

In [13]:
%%sql

INSERT INTO courses
    (course_name, course_author, course_status, course_published_dt)
VALUES
    ('Programming using Python', 'Bob Dillon', 'published', '2020-09-30'),
    ('Data Engineering using Python', 'Bob Dillon', 'published', '2020-07-15'),
    ('Data Engineering using Scala', 'Elvis Presley', 'draft', null),
    ('Programming using Scala' , 'Elvis Presley' , 'published' , '2020-05-12'),
    ('Programming using Java' , 'Mike Jack' , 'inactive' , '2020-08-10'),
    ('Web Applications - Python Flask' , 'Bob Dillon' , 'inactive' , '2020-07-20'),
    ('Web Applications - Java Spring' , 'Bob Dillon' , 'draft' , null),
    ('Pipeline Orchestration - Python' , 'Bob Dillon' , 'draft' , null),
    ('Streaming Pipelines - Python' , 'Bob Dillon' , 'published' , '2020-10-05'),
    ('Web Applications - Scala Play' , 'Elvis Presley' , 'inactive' , '2020-09-30'),
    ('Web Applications - Python Django' , 'Bob Dillon' , 'published' , '2020-06-23'),
    ('Server Automation - Ansible' , 'Uncle Sam' , 'published' , '2020-07-05');

 * postgresql://itversity_sms_user:***@localhost:5432/itversity_sms_db
12 rows affected.

[]

In [15]:
%config SqlMagic.style = 'PLAIN_COLUMNS'

In [17]:
%config SqlMagic.style = 'MARKDOWN'

In [21]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp313-cp313-macosx_10_13_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.2-cp313-cp313-macosx_14_0_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp313-cp313-macosx_10_13_x86_64.whl (10.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 52.6 MB/s  0:00:00m0:00:01
Downloading numpy-2.4.2-cp313-cp313-macosx_14_0_x86_64.whl (6.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 56.1 MB/s  0:00:00
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.2 pandas-3.0.1

In [22]:
%config SqlMagic.autopandas = True
import pandas as pd

In [3]:
%load_ext sql
import os
os.environ['DATABASE_URL'] = "postgresql://itversity_sms_user:itversity@localhost:5432/itversity_sms_db"
%config SqlMagic.autopandas = True

In [6]:
!pip install --upgrade "prettytable<3.0.0"

Collecting prettytable<3.0.0
  Downloading prettytable-2.5.0-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: wcwidth in /opt/miniconda3/lib/python3.13/site-packages (from prettytable<3.0.0) (0.2.13)
Downloading prettytable-2.5.0-py3-none-any.whl (24 kB)
Installing collected packages: prettytable
  Attempting uninstall: prettytable
    Found existing installation: prettytable 3.17.0
    Uninstalling prettytable-3.17.0:
      Successfully uninstalled prettytable-3.17.0
Successfully installed prettytable-2.5.0

In [8]:
from sqlalchemy import create_engine
import pandas as pd

# 1. Create the connection engine
engine = create_engine("postgresql://itversity_sms_user:itversity@localhost:5432/itversity_sms_db")

# 2. Run the query and load directly into a DataFrame
query = "SELECT * FROM courses ORDER BY course_id"
df_courses = pd.read_sql(query, engine)

# 3. Display the result
df_courses

,course_id,course_name,course_author,course_status,course_published_dt
0,1,Programming using Python,Bob Dillon,published,2020-09-30
1,2,Data Engineering using Python,Bob Dillon,published,2020-07-15
2,3,Data Engineering using Scala,Elvis Presley,draft,None
3,4,Programming using Scala,Elvis Presley,published,2020-05-12
4,5,Programming using Java,Mike Jack,inactive,2020-08-10
5,6,Web Applications - Python Flask,Bob Dillon,inactive,2020-07-20
6,7,Web Applications - Java Spring,Bob Dillon,draft,None
7,8,Pipeline Orchestration - Python,Bob Dillon,draft,None
8,9,Streaming Pipelines - Python,Bob Dillon,published,2020-10-05
9,10,Web Applications - Scala Play,Elvis Presley,inactive,2020-09-30
10,11,Web Applications - Python Django,Bob Dillon,published,2020-06-23
11,12,Server Automation - Ansible,Uncle Sam,published,2020-07-05

In [ ]:
# 1. Create the connection engine
engine = create_engine("postgresql://itversity_sms_user:itversity@localhost:5432/itversity_sms_db")

# 2. Run the query and load directly into a DataFrame
query = "SELECT * FROM courses ORDER BY course_id"
df_courses = pd.read_sql(query, engine)

# 3. Display the result
df_courses

In [16]:
# 1. Create the connection engine
engine = create_engine("postgresql://itversity_sms_user:itversity@localhost:5432/itversity_sms_db")

# 2. Run the query and load directly into a DataFrame
query = "SELECT *" \
"FROM courses " \
"WHERE course_status in ('inactive','draft')"

df_courses = pd.read_sql(query, engine)

# 3. Display the result
df_courses

,course_id,course_name,course_author,course_status,course_published_dt
0,3,Data Engineering using Scala,Elvis Presley,draft,None
1,5,Programming using Java,Mike Jack,inactive,2020-08-10
2,6,Web Applications - Python Flask,Bob Dillon,inactive,2020-07-20
3,7,Web Applications - Java Spring,Bob Dillon,draft,None
4,8,Pipeline Orchestration - Python,Bob Dillon,draft,None
5,10,Web Applications - Scala Play,Elvis Presley,inactive,2020-09-30

In [23]:
from sqlalchemy import text

query = text("""
    SELECT *
    FROM courses
    WHERE course_name LIKE '%Python%' or course_name LIKE '%SCALA%'
""")

df_courses = pd.read_sql(query, engine)

df_courses

,course_id,course_name,course_author,course_status,course_published_dt
0,1,Programming using Python,Bob Dillon,published,2020-09-30
1,2,Data Engineering using Python,Bob Dillon,published,2020-07-15
2,6,Web Applications - Python Flask,Bob Dillon,inactive,2020-07-20
3,8,Pipeline Orchestration - Python,Bob Dillon,draft,None
4,9,Streaming Pipelines - Python,Bob Dillon,published,2020-10-05
5,11,Web Applications - Python Django,Bob Dillon,published,2020-06-23

In [25]:
from sqlalchemy import text

query = text("""
    SELECT 
             course_author,
             count(*) as course_count
    FROM courses
    WHERE course_status = 'published'
    GROUP BY course_author
""")

df_courses = pd.read_sql(query, engine)

df_courses

  course_status  course_count
0     published             6
1      inactive             3
2         draft             3

In [27]:
from sqlalchemy import text

query = text("""
    SELECT 
             course_author,
             count(*) as course_author_count
    FROM courses
    WHERE course_status = 'published'
    GROUP BY course_author
""")

df_courses = pd.read_sql(query, engine)

df_courses

   course_author  course_author_count
0     Bob Dillon                    4
1  Elvis Presley                    1
2      Uncle Sam                    1

In [34]:
from sqlalchemy import text

query = text("""
    SELECT *
    FROM courses
    WHERE course_status = 'draft'
      AND (
            course_name LIKE '%Python%'
         OR course_name LIKE '%Scala%'
      )
""")

df_courses = pd.read_sql(query, engine)
df_courses

,course_id,course_name,course_author,course_status,course_published_dt
0,3,Data Engineering using Scala,Elvis Presley,draft,None
1,8,Pipeline Orchestration - Python,Bob Dillon,draft,None

In [38]:
from sqlalchemy import text

query = text("""
      SELECT 
             course_author,
             count(*) as course_count
      FROM courses
      WHERE course_status = 'published'
      GROUP BY course_author
      HAVING count(*)>1
      
""")

df_courses = pd.read_sql(query, engine)
df_courses

  course_author  course_count
0    Bob Dillon             4