# Exercises - Basic SQL Queries

Here are some of the exercises for which you can write SQL queries to self evaluate using all the concepts we have learnt to write SQL Queries.
* All the exercises are based on retail tables.
* We have already setup the tables and also populated the data.
* We will use all the 6 tables in retail database as part of these exercises.

In [ ]:
%load_ext sql

In [1]:
%env DATABASE_URL=postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db

env: DATABASE_URL=postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db

In [4]:
%config SqlMagic.style = 'MARKDOWN'

In [5]:
%config SqlMagic.autopandas = True
import pandas as pd

In [8]:
%load_ext sql
import os
os.environ['DATABASE_URL'] = "postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db"
%config SqlMagic.autopandas = True

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [37]:
from sqlalchemy import create_engine
import pandas as pd

# 1. Create the connection engine
engine = create_engine("postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db")

# 2. Run the query and load directly into a DataFrame
query = "SELECT * FROM orders"
df_courses = pd.read_sql(query, engine)

# 3. Display the result
df_courses

       order_id order_date  order_customer_id     order_status
0             1 2013-07-25              11599           CLOSED
1             2 2013-07-25                256  PENDING_PAYMENT
2             3 2013-07-25              12111         COMPLETE
3             4 2013-07-25               8827           CLOSED
4             5 2013-07-25              11318         COMPLETE
...         ...        ...                ...              ...
68878     68879 2014-07-09                778         COMPLETE
68879     68880 2014-07-13               1117         COMPLETE
68880     68881 2014-07-19               2518  PENDING_PAYMENT
68881     68882 2014-07-22              10000          ON_HOLD
68882     68883 2014-07-23               5533         COMPLETE

[68883 rows x 4 columns]

## Exercise 1 - Customer order count

Get order count per customer for the month of 2014 January.

* Tables - `orders` and `customers`
* Data should be sorted in descending order by count and ascending order by customer id.
* Output should contain `customer_id`, `customer_fname`, `customer_lname` and `customer_order_count`.

In [57]:
from sqlalchemy import create_engine
import pandas as pd

# 1. Create the connection engine
engine = create_engine("postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db")

# 2. Run the query and load directly into a DataFrame
query = """ 
SELECT 
    c.customer_id,
    c.customer_fname,
    c.customer_lname,
    count(o.order_id)

FROM customers c 
LEFT JOIN orders o on o.order_customer_id = c.customer_id AND to_char(o.order_date::date, 'yyyy-MM') = '2014-01'
GROUP BY 1,2,3
HAVING count(o.order_id) > 0
ORDER BY 4 DESC, 1 ASC


"""
df_courses = pd.read_sql(query, engine)

# 3. Display the result
df_courses

      customer_id customer_fname customer_lname  count
0            8622        Shirley          Smith      5
1            9676        Theresa          Smith      5
2               7        Melissa         Wilcox      4
3             222          Frank           Ruiz      4
4            2444        Kenneth          Smith      4
...           ...            ...            ...    ...
4691        12424           Judy       Phillips      1
4692        12426         Jordan         Valdez      1
4693        12427           Mary          Smith      1
4694        12430         Hannah          Brown      1
4695        12432         Angela          Smith      1

[4696 rows x 4 columns]

## Exercise 2 - Dormant Customers

Get the customer details who have not placed any order for the month of 2014 January.
* Tables - `orders` and `customers`
* Output Columns - **All columns from customers as is**
* Data should be sorted in ascending order by `customer_id`
* Output should contain all the fields from `customers`
* Make sure to run below provided validation queries and validate the output.

Get the difference
Get the count using solution query, both the difference and this count should match

SELECT count(*)
FROM customers;

SELECT count(DISTINCT order_customer_id)
FROM orders
WHERE to_char(order_date, 'yyyy-MM') = '2014-01';

(Hint: You can use `NOT IN` or `NOT EXISTS` or `OUTER JOIN` to solve this problem).

In [29]:
from sqlalchemy import create_engine
import pandas as pd

# 1. Create the connection engine
engine = create_engine("postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db")

# 2. Run the query and load directly into a DataFrame
query = """ 
SELECT DISTINCT
    c.*,
    o.*

FROM customers c 
LEFT JOIN orders o on o.order_customer_id = c.customer_id AND to_char(o.order_date::date, 'yyyy-MM') = '2014-01'
WHERE order_id IS NULL

"""
df_courses = pd.read_sql(query, engine)

# 3. Display the result
df_courses

,customer_id,customer_fname,customer_lname,customer_email,customer_password,customer_street,customer_city,customer_state,customer_zipcode,order_id,order_date,order_customer_id,order_status
0,1,Richard,Hernandez,XXXXXXXXX,XXXXXXXXX,6303 Heather Plaza,Brownsville,TX,78521,None,None,None,None
1,2,Mary,Barrett,XXXXXXXXX,XXXXXXXXX,9526 Noble Embers Ridge,Littleton,CO,80126,None,None,None,None
2,3,Ann,Smith,XXXXXXXXX,XXXXXXXXX,3422 Blue Pioneer Bend,Caguas,PR,00725,None,None,None,None
3,4,Mary,Jones,XXXXXXXXX,XXXXXXXXX,8324 Little Common,San Marcos,CA,92069,None,None,None,None
4,5,Robert,Hudson,XXXXXXXXX,XXXXXXXXX,10 Crystal River Mall,Caguas,PR,00725,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7734,12428,Jeffrey,Travis,XXXXXXXXX,XXXXXXXXX,1552 Burning Dale Highlands,Caguas,PR,00725,None,None,None,None
7735,12429,Mary,Smith,XXXXXXXXX,XXXXXXXXX,92 Sunny Bear Villas,Gardena,CA,90247,None,None,None,None
7736,12433,Benjamin,Garcia,XXXXXXXXX,XXXXXXXXX,5459 Noble Brook Landing,Levittown,NY,11756,None,None,None,None
7737,12434,Mary,Mills,XXXXXXXXX,XXXXXXXXX,9720 Colonial Parade,Caguas,PR,00725,None,None,None,None
7738,12435,Laura,Horton,XXXXXXXXX,XXXXXXXXX,5736 Honey Downs,Summerville,SC,29483,None,None,None,None

## Exercise 3 - Revenue Per Customer

 Get the revenue generated by each customer for the month of 2014 January
 * Tables - `orders`, `order_items` and `customers`
 * Data should be sorted in descending order by revenue and then ascending order by `customer_id`
 * Output should contain `customer_id`, `customer_fname`, `customer_lname`, `customer_revenue`.
 * If there are no orders placed by customer, then the corresponding revenue for a given customer should be 0.
 * Consider only `COMPLETE` and `CLOSED` orders

In [59]:
from sqlalchemy import text

query = text("""
SELECT
    c.customer_id,
    c.customer_fname,
    c.customer_lname,
    COALESCE(SUM(oi.order_item_subtotal), 0) AS customer_revenue
FROM customers c
LEFT JOIN orders o
       ON o.order_customer_id = c.customer_id
      AND o.order_status IN ('COMPLETE', 'CLOSED')
      AND to_char(o.order_date, 'YYYY-MM') = '2014-01'
LEFT JOIN order_items oi
       ON oi.order_item_order_id = o.order_id-30.48
GROUP BY 1,2,3
ORDER BY 4 DESC, 1 ASC
""")

df_courses = pd.read_sql(query, engine)
df_courses

       customer_id customer_fname customer_lname  customer_revenue
0                1        Richard      Hernandez               0.0
1                2           Mary        Barrett               0.0
2                3            Ann          Smith               0.0
3                4           Mary          Jones               0.0
4                5         Robert         Hudson               0.0
...            ...            ...            ...               ...
12430        12431           Mary           Rios               0.0
12431        12432         Angela          Smith               0.0
12432        12433       Benjamin         Garcia               0.0
12433        12434           Mary          Mills               0.0
12434        12435          Laura         Horton               0.0

[12435 rows x 4 columns]